# Generated by Django 5.2.4 on 2026-01-19 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=9, unique=True, verbose_name='Nome')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ano letivo',
                'verbose_name_plural': 'Anos letivos',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da turma')),
                ('tipo_contexto', models.CharField(choices=[('ENSINO_BASICO_TIC', 'Ensino Basico (TIC)'), ('ENSINO_PROFISSIONAL_UFCD', 'Ensino Profissional (UFCD)')], default='ENSINO_BASICO_TIC', max_length=30, verbose_name='Tipo de contexto')),
                ('ciclo', models.CharField(choices=[('2C', '2º Ciclo'), ('3C', '3º Ciclo'), ('NA', 'Nao aplica')], default='NA', max_length=2, verbose_name='Ciclo')),
                ('ano_escolaridade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de escolaridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='nucleo.anoletivo', verbose_name='Ano letivo')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
                'unique_together': {('ano_letivo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='nucleo.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['turma__nome', 'nome_completo'],
                'unique_together': {('turma', 'numero', 'nome_completo')},
            },
        ),
    ]
