# Generated by Django 5.2.4 on 2026-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ciclo',
            field=models.CharField(choices=[('2C', '2º Ciclo'), ('3C', '3º Ciclo'), ('SEC', 'Ensino Secundario'), ('NA', 'Nao aplica')], default='NA', max_length=3, verbose_name='Ciclo'),
        ),
    ]
