# Generated by Django 5.2.4 on 2026-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_alter_aluno_numero_alter_turma_ciclo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aluno',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ciclo',
            field=models.CharField(choices=[('2C', '2º Ciclo'), ('3C', '3º Ciclo'), ('SEC', 'Ensino Secundário')], default='2C', max_length=3, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_contexto',
            field=models.CharField(choices=[('ENSINO_BASICO_TIC', 'Ensino Básico (TIC)'), ('ENSINO_SECUNDARIO', 'Ensino Secundário'), ('ENSINO_PROFISSIONAL_UFCD', 'Ensino Profissional (UFCD)')], default='ENSINO_BASICO_TIC', max_length=30, verbose_name='Tipo de contexto'),
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('turma', 'numero'), name='uniq_aluno_numero_por_turma_quando_preenchido'),
        ),
    ]
