# Generated by Django 5.2.4 on 2026-01-19 20:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCognitivaTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(verbose_name='Periodo (1 a 3)')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da avaliacao')),
                ('peso_percentual', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso percentual (0-100)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_tic', to='nucleo.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Avaliacao cognitiva TIC',
                'verbose_name_plural': 'Avaliacoes cognitivas TIC',
                'ordering': ['turma__nome', 'periodo', 'nome'],
                'unique_together': {('turma', 'periodo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='BoletimPeriodoTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(verbose_name='Periodo (1 a 3)')),
                ('estado', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Estado')),
                ('autoavaliacao_nivel', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Autoavaliacao (nivel 1 a 5)')),
                ('nota_cognitivo_80', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota cognitivo (0 a 80)')),
                ('pontuacao_atitudes_20', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Atitudes (0 a 20)')),
                ('nota_final_100', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nota final (0 a 100)')),
                ('mencao_qualitativa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mencao qualitativa')),
                ('nivel_sge', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nivel SGE (1 a 5)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletins_tic', to='nucleo.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletins_tic', to='nucleo.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Boletim TIC (periodo)',
                'verbose_name_plural': 'Boletins TIC (periodos)',
                'ordering': ['turma__nome', 'periodo', 'aluno__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='AtitudesPeriodoTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilidade_integridade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Responsabilidade e integridade (0-3)')),
                ('excelencia_exigencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Excelencia e exigencia (0-6)')),
                ('curiosidade_reflexao_inovacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Curiosidade, reflexao e inovacao (0-2)')),
                ('cidadania_participacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Cidadania e participacao (0-4)')),
                ('liberdade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Liberdade (0-5)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('boletim_periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atitudes', to='tic.boletimperiodotic', verbose_name='Boletim TIC (periodo)')),
            ],
            options={
                'verbose_name': 'Atitudes TIC (periodo)',
                'verbose_name_plural': 'Atitudes TIC (periodos)',
            },
        ),
        migrations.CreateModel(
            name='NotaAvaliacaoCognitivaTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_0a100', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Nota (0 a 100)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_avaliacoes_tic', to='nucleo.aluno', verbose_name='Aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='tic.avaliacaocognitivatic', verbose_name='Avaliacao')),
            ],
            options={
                'verbose_name': 'Nota avaliacao cognitiva TIC',
                'verbose_name_plural': 'Notas avaliacoes cognitivas TIC',
            },
        ),
        migrations.AddIndex(
            model_name='boletimperiodotic',
            index=models.Index(fields=['turma', 'periodo'], name='tic_boletim_turma_i_5b8e05_idx'),
        ),
        migrations.AddIndex(
            model_name='boletimperiodotic',
            index=models.Index(fields=['aluno', 'periodo'], name='tic_boletim_aluno_i_469486_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boletimperiodotic',
            unique_together={('turma', 'aluno', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='notaavaliacaocognitivatic',
            unique_together={('avaliacao', 'aluno')},
        ),
    ]
