# Generated by Django 5.2.4 on 2026-02-10 11:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic', '0002_rename_boletim_periodo_to_boletim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atitudesperiodotic',
            options={'verbose_name': 'Atitudes TIC (período)', 'verbose_name_plural': 'Atitudes TIC (períodos)'},
        ),
        migrations.AlterField(
            model_name='atitudesperiodotic',
            name='boletim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atitudes', to='tic.boletimperiodotic', verbose_name='Boletim TIC (período)'),
        ),
        migrations.AlterField(
            model_name='atitudesperiodotic',
            name='cidadania_participacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Cidadania e participação (0-4)'),
        ),
        migrations.AlterField(
            model_name='atitudesperiodotic',
            name='curiosidade_reflexao_inovacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Curiosidade, reflexão e inovação (0-2)'),
        ),
        migrations.AlterField(
            model_name='atitudesperiodotic',
            name='excelencia_exigencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Excelência e exigência (0-6)'),
        ),
        migrations.AlterField(
            model_name='avaliacaocognitivatic',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.º Período'), (2, '2.º Período'), (3, '3.º Período')], verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='boletimperiodotic',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.º Período'), (2, '2.º Período'), (3, '3.º Período')], verbose_name='Período'),
        ),
    ]
