# Generated by Django 5.2.4 on 2026-02-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic', '0003_alter_atitudesperiodotic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaocognitivatic',
            options={'ordering': ['turma__nome', 'periodo', 'nome'], 'verbose_name': 'Avaliação cognitiva TIC', 'verbose_name_plural': 'Avaliações cognitivas TIC'},
        ),
        migrations.AlterModelOptions(
            name='boletimperiodotic',
            options={'ordering': ['turma__nome', 'periodo', 'aluno__nome_completo'], 'verbose_name': 'Boletim TIC (período)', 'verbose_name_plural': 'Boletins TIC (períodos)'},
        ),
        migrations.AlterModelOptions(
            name='notaavaliacaocognitivatic',
            options={'verbose_name': 'Nota avaliação cognitiva TIC', 'verbose_name_plural': 'Notas avaliações cognitivas TIC'},
        ),
        migrations.RemoveField(
            model_name='boletimperiodotic',
            name='nota_cognitivo_80',
        ),
        migrations.RemoveField(
            model_name='boletimperiodotic',
            name='pontuacao_atitudes_20',
        ),
        migrations.AddField(
            model_name='boletimperiodotic',
            name='media_cognitiva_100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Média cognitiva (0 a 100)'),
        ),
        migrations.AddField(
            model_name='boletimperiodotic',
            name='nota_atitudes_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Atitudes (0 a 20)'),
        ),
        migrations.AddField(
            model_name='boletimperiodotic',
            name='nota_cognitiva_80',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nota cognitiva (0 a 80)'),
        ),
        migrations.AlterField(
            model_name='avaliacaocognitivatic',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome da avaliação'),
        ),
        migrations.AlterField(
            model_name='boletimperiodotic',
            name='autoavaliacao_nivel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Autoavaliação (nível 1 a 5)'),
        ),
        migrations.AlterField(
            model_name='boletimperiodotic',
            name='mencao_qualitativa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Menção qualitativa'),
        ),
        migrations.AlterField(
            model_name='boletimperiodotic',
            name='nivel_sge',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nível SGE (1 a 5)'),
        ),
        migrations.AlterField(
            model_name='boletimperiodotic',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='notaavaliacaocognitivatic',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='tic.avaliacaocognitivatic', verbose_name='Avaliação'),
        ),
    ]
